// need to be able to generate multiple index entry files
// e.g. main, webworker, node, etc.

import { readJSONSync, writeJSONSync } from 'fs-extra';

// sub imports can be generated by finding `init` files? or should it just be a manual list?
const subImports = [
    ['./accessibility', './lib/accessibility'],
    ['./advanced-blend-modes', './lib/advanced-blend-modes'],
    ['./app', './lib/app'],
    ['./dds', './lib/compressed-textures/dds'],
    ['./ktx', './lib/compressed-textures/ktx'],
    ['./ktx2', './lib/compressed-textures/ktx2'],
    ['./basis', './lib/compressed-textures/basis'],
    ['./events', './lib/events'],
    ['./dom', './lib/dom'],
    ['./filters', './lib/filters'],
    ['./math-extras', './lib/math-extras'],
    ['./sprite-tiling', './lib/scene/sprite-tiling'],
    ['./text', './lib/scene/text'],
    ['./text-bitmap', './lib/scene/text-bitmap'],
    ['./text-html', './lib/scene/text-html'],
    ['./graphics', './lib/scene/graphics'],
    ['./mesh', './lib/scene/mesh'],
    ['./prepare', './lib/prepare'],
    ['./unsafe-eval', './lib/unsafe-eval'],
    ['./sprite-nine-slice', './lib/scene/sprite-nine-slice'],
    ['./particle-container', './lib/scene/particle-container'],
];

interface ExportField
{
    import: {
        default: string;
        types?: string;
    };
    require: {
        default: string;
        types?: string;
    };
}

const exportFields: Record<string, ExportField> = {
    '.': {
        import: {
            types: './lib/index.d.ts',
            default: './lib/index.mjs',
        },
        require: {
            types: './lib/index.d.ts',
            default: './lib/index.js',
        },
    },
    './browser': {
        import: {
            default: './lib/environment-browser/browserAll.mjs',
        },
        require: {
            default: './lib/environment-browser/browserAll.js',
        },
    },
    './webworker': {
        import: {
            default: './lib/environment-webworker/webworkerAll.mjs',
        },
        require: {
            default: './lib/environment-webworker/webworkerAll.js',
        },
    },
    './gif': {
        import: {
            types: './lib/gif/init.d.ts',
            default: './lib/gif/init.mjs',
        },
        require: {
            types: './lib/gif/init.d.ts',
            default: './lib/gif/init.js',
        },
    },
    './app/application': {
        import: {
            default: './lib/app/Application.mjs'
        },
        require: {
            default: './lib/app/Application.js'
        }
    },
    './rendering': {
        import: {
            default: './lib/rendering/index.mjs'
        },
        require: {
            default: './lib/rendering/index.js'
        }
    },
    './rendering/init': {
        import: {
            default: './lib/rendering/init.mjs'
        },
        require: {
            default: './lib/rendering/init.js'
        }
    },
    './spritesheet/init': {
        import: {
            default: './lib/spritesheet/init.mjs'
        },
        require: {
            default: './lib/spritesheet/init.js'
        }
    },
    './environment/adapter': {
        import: {
            default: './lib/environment/adapter.mjs'
        },
        require: {
            default: './lib/environment/adapter.js'
        }
    },
    './scene/graphics': {
        import: {
            default: './lib/scene/graphics/shared/Graphics.mjs'
        },
        require: {
            default: './lib/scene/graphics/shared/Graphics.js'
        }
    },
    './scene/sprite': {
        import: {
            default: './lib/scene/sprite/Sprite.mjs'
        },
        require: {
            default: './lib/scene/sprite/Sprite.js'
        }
    },
    './mini-program/*': {
        import: {
            default: './lib/mini-program/*.mjs'
        },
        require: {
            default: './lib/mini-program/*.js'
        }
    },
    './assets': {
        import: {
            default: './lib/assets/index.mjs'
        },
        require: {
            default: './lib/assets/index.js'
        }
    },
};
const sideEffects = [
    './lib/environment-browser/browserAll.*',
    './lib/environment-webworker/webworkerAll.*',
    './lib/index.*',
    './lib/rendering/init.*',
    './lib/spritesheet/init.*',
    './lib/rendering/renderers/shared/texture/utils/textureFrom.*',
    './lib/gif/init.*',
    './lib/mini-program/init-app.*'
];

for (const [name, path] of subImports)
{
    exportFields[name] = {
        import: {
            default: `${path}/init.mjs`,
        },
        require: {
            default: `${path}/init.js`,
        },
    };
    sideEffects.push(`${path}/init.*`);
}

const pkg = readJSONSync('./package.json');

pkg.exports = exportFields;
pkg.sideEffects = sideEffects;

writeJSONSync('./package.json', pkg, { spaces: 2 });
